require('./document.spec')
require('./encrypt.spec')
require('./field.spec')
require('./object.spec')
require('./page.spec')
require('./painter.spec')
require('./parser.spec')
require('./signer.spec')